"""readds profarray

Revision ID: 01236e42294f
Revises: 967086f2b287
Create Date: 2024-02-13 14:36:15.716822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01236e42294f'
down_revision = '967086f2b287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('proficienciesArr', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'proficienciesArr')
    # ### end Alembic commands ###
