"""initial migration

Revision ID: 161497f78682
Revises: 
Create Date: 2024-02-12 09:38:35.561102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161497f78682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilityscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('str_score', sa.Integer(), nullable=False),
    sa.Column('dex_score', sa.Integer(), nullable=False),
    sa.Column('con_score', sa.Integer(), nullable=False),
    sa.Column('int_score', sa.Integer(), nullable=False),
    sa.Column('wis_score', sa.Integer(), nullable=False),
    sa.Column('cha_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('ability_bonuses', sa.JSON(), nullable=True),
    sa.Column('creature_type', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('starting_proficiencies', sa.JSON(), nullable=True),
    sa.Column('dnd_race_api_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dnd_class', sa.JSON(), nullable=False),
    sa.Column('subclasses', sa.JSON(), nullable=True),
    sa.Column('dnd_class_level', sa.JSON(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('hit_die', sa.String(), nullable=True),
    sa.Column('proficiency_choices', sa.JSON(), nullable=True),
    sa.Column('proficiencies', sa.JSON(), nullable=True),
    sa.Column('saving_throws', sa.JSON(), nullable=True),
    sa.Column('abilityscores_id', sa.Integer(), nullable=True),
    sa.Column('feats', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('background', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('backstory', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('dnd_class_api_url', sa.String(), nullable=False),
    sa.Column('dnd_class_levels_api_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['abilityscores_id'], ['abilityscores.id'], name=op.f('fk_characters_abilityscores_id_abilityscores')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_characters_party_id_parties')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_characters_race_id_races')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('races')
    op.drop_table('parties')
    op.drop_table('abilityscores')
    # ### end Alembic commands ###
