"""changes profarray to JSON

Revision ID: 45952f8bdab9
Revises: ec48ed73c30e
Create Date: 2024-02-12 10:32:41.141825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45952f8bdab9'
down_revision = 'ec48ed73c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('proficienciesArr',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('proficienciesArr',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
