"""adds prof_mod column

Revision ID: 645da19699f1
Revises: f34180bc1e3d
Create Date: 2024-02-09 14:22:30.368660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645da19699f1'
down_revision = 'f34180bc1e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prof_mod', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('prof_mod')

    # ### end Alembic commands ###
