"""removes profarray

Revision ID: 967086f2b287
Revises: c9accb215f40
Create Date: 2024-02-13 14:33:44.443776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967086f2b287'
down_revision = 'c9accb215f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'gold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_characters_party_id_parties', 'characters', type_='foreignkey')
    op.drop_column('characters', 'proficienciesArr')
    op.drop_column('characters', 'party_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('proficienciesArr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_characters_party_id_parties', 'characters', 'parties', ['party_id'], ['id'])
    op.alter_column('characters', 'gold',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
