"""adds proficienciesArr column

Revision ID: ec48ed73c30e
Revises: 161497f78682
Create Date: 2024-02-12 09:53:59.669126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec48ed73c30e'
down_revision = '161497f78682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficienciesArr', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('proficienciesArr')

    # ### end Alembic commands ###
